- platform: generic_thermostat
  name: Dining Room AC
  unique_id: climate.dining_room_ac
  heater: input_boolean.dining_room_ac_power
  target_sensor: sensor.dining_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 0.5
  cold_tolerance: 0
  hot_tolerance: 0.7