- platform: generic_thermostat
  name: Dining Room AC
  unique_id: climate.dining_room_ac
  heater: switch.dining_room_ac_switch
  target_sensor: sensor.dining_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5

- platform: generic_thermostat
  name: Eli's Room AC
  unique_id: climate.elis_room_ac
  heater: switch.elis_room_ac_switch
  target_sensor: sensor.elis_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5

- platform: generic_thermostat
  name: Elena's Room AC
  unique_id: climate.elenas_room_ac
  heater: switch.elenas_room_ac_switch
  target_sensor: sensor.elenas_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5

- platform: generic_thermostat
  name: Living Room AC
  unique_id: climate.living_room_ac
  heater: switch.living_room_ac_switch
  target_sensor: sensor.dining_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5

- platform: generic_thermostat
  name: Study Room AC
  unique_id: climate.study_room_ac
  heater: switch.study_room_ac_switch
  target_sensor: sensor.study_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5

- platform: generic_thermostat
  name: Parents' Room AC
  unique_id: climate.parents_room_ac
  heater: switch.parents_room_ac_switch
  target_sensor: sensor.parents_room_temperature
  ac_mode: true
  min_temp: 23
  max_temp: 27
  target_temp: 27
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 10
  hot_tolerance: -5