- platform: local_file
  name: Recent Main Door Snapshot 1
  file_path: /media/main_door_camera/snapshot.png
- platform: local_file
  name: Recent Main Door Snapshot 2
  file_path: /media/main_door_camera/snapshot.png
- platform: local_file
  name: Recent Main Door Snapshot 3
  file_path: /media/main_door_camera/snapshot.png