# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.18.1
    - 192.168.18.104

frontend:
  themes: !include themes.yaml

recorder: !include recorder.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch: !include rest-switches.yaml
template: !include_dir_merge_list template-entities/
sensor: !include sensors.yaml
rest: !include rest-sensors.yaml

google_assistant: !include google_assistant.yaml

shell_command: !include shell-commands.yaml

zha:
  zigpy_config:
    network:
      channel: 25             # What channel the radio should try to use.
      channels: [15, 20, 25]  # Channel mask
    ota:
      disable_default_providers: 
        - ikea

logger:
  default: warn