# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.18.1

frontend:
  themes: !include themes.yaml

# Text to speech
tts:
  - platform: google_translate

recorder:
  purge_keep_days: 14
  db_url: sqlite:////share/database/home-assistant_v2.db


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch: !include switches.yaml
fan: !include fans.yaml
climate: !include aircons.yaml
template: !include template-sensors.yaml
sensor: !include sensors.yaml
cover: !include covers.yaml

google_assistant: !include google_assistant.yaml

zha:
  zigpy_config:
    network:
      channel: 25             # What channel the radio should try to use.
      channels: [15, 20, 25]  # Channel mask
    ota:
      ikea_provider: false

logger:
  default: warn