- platform: cover_rf_time_based
  devices:
    kitchen_blinds:
      name: Kitchen Blinds
      travelling_time_up: 14
      travelling_time_down: 14
      close_script_entity_id: script.kitchen_blinds_down
      stop_script_entity_id: script.kitchen_blinds_stop
      open_script_entity_id: script.kitchen_blinds_up