- platform: template
  fans:
    elis_room_fan:
      friendly_name: "Eli's Room Fan"
      unique_id: fan.elis_room_fan
      value_template: "{{ states('input_boolean.elis_room_fan_power') }}"
      percentage_template: "{{ states('input_number.elis_room_fan_speed') | int }}"
      direction_template: "{{ states('input_select.elis_room_fan_direction') }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.elis_room_fan_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.elis_room_fan_power
      set_percentage:
        - service: input_boolean.turn_{{ 'on' if percentage > 0 else 'off' }}
          target:
            entity_id: input_boolean.elis_room_fan_power
        - service: input_number.set_value
          target:
            entity_id: input_number.elis_room_fan_speed
          data:
            value: "{{ percentage }}"
      set_direction:
        service: script.fan_set_direction
        data:
          target_fan: Eli's Room Fan
          direction: "{{ direction }}"
      speed_count: 6

    elenas_room_fan:
      friendly_name: "Elena's Room Fan"
      unique_id: fan.elenas_room_fan
      value_template: "{{ states('input_boolean.elenas_room_fan_power') }}"
      percentage_template: "{{ states('input_number.elenas_room_fan_speed') | int }}"
      direction_template: "{{ states('input_select.elenas_room_fan_direction') }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.elenas_room_fan_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.elenas_room_fan_power
      set_percentage:
        - service: input_boolean.turn_{{ 'on' if percentage > 0 else 'off' }}
          target:
            entity_id: input_boolean.elenas_room_fan_power
        - service: input_number.set_value
          target:
            entity_id: input_number.elenas_room_fan_speed
          data:
            value: "{{ percentage }}"
      set_direction:
        service: script.fan_set_direction
        data:
          target_fan: Elena's Room Fan
          direction: "{{ direction }}"
      speed_count: 6

#    #study_room_fan:
      #friendly_name: "Study Room Fan"
      #unique_id: fan.study_room_fan
      #value_template: "{{ states('input_boolean.study_room_fan_power') }}"
      #percentage_template: "{{ states('input_number.study_room_fan_speed') | int }}"
      #direction_template: "{{ states('input_select.study_room_fan_direction') }}"
      #turn_on:
        #service: input_boolean.turn_on
        #target:
          #entity_id: input_boolean.study_room_fan_power
      #turn_off:
        #service: input_boolean.turn_off
        #target:
          #entity_id: input_boolean.study_room_fan_power
      #set_percentage:
        #- service: input_boolean.turn_{{ 'on' if percentage > 0 else 'off' }}
          #target:
            #entity_id: input_boolean.study_room_fan_power
        #- service: input_number.set_value
          #target:
            #entity_id: input_number.study_room_fan_speed
          #data:
            #value: "{{ percentage }}"
      #set_direction:
        #service: script.fan_set_direction
        #data:
          #target_fan: Study Room Fan
          #direction: "{{ direction }}"
      #speed_count: 6
      
    parents_room_fan:
      friendly_name: "Parents' Room Fan"
      unique_id: fan.parents_room_fan
      value_template: "{{ states('input_boolean.parents_room_fan_power') }}"
      percentage_template: "{{ states('input_number.parents_room_fan_speed') | int }}"
      direction_template: "{{ states('input_select.parents_room_fan_direction') }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.parents_room_fan_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.parents_room_fan_power
      set_percentage:
        - service: input_boolean.turn_{{ 'on' if percentage > 0 else 'off' }}
          target:
            entity_id: input_boolean.parents_room_fan_power
        - service: input_number.set_value
          target:
            entity_id: input_number.parents_room_fan_speed
          data:
            value: "{{ percentage }}"
      set_direction:
        service: script.fan_set_direction
        data:
          target_fan: Parents' Room Fan
          direction: "{{ direction }}"
      speed_count: 6
      
