- platform: group
  name: Elena's Room Lights
  unique_id: light.elenas_room_lights
  entities:
    - light.elenas_room_bulb_1_entity
    - light.elenas_room_bulb_2_entity
    - light.elenas_room_bulb_3_entity

- platform: group
  name: Eli's Room Lights
  unique_id: light.elis_room_lights
  entities:
    - light.elis_room_bulb_1_entity
    - light.elis_room_bulb_2_entity
    - light.elis_room_bulb_3_entity

- platform: group
  name: Junior Bathroom Lights
  unique_id: light.junior_bathroom_lights
  entities:
    - light.junior_bathroom_pendant_light_entity
    - light.junior_bathroom_ceiling_light_entity

- platform: group
  name: Hallway Lights
  unique_id: light.hallway_lights
  entities:
    - light.hallway_bulb_1_entity
    - light.hallway_bulb_2_entity

- platform: group
  name: Dining Room Lights
  unique_id: light.dining_room_lights
  entities:
    - light.dining_room_bulb_1_entity
    - light.dining_room_bulb_2_entity
    - light.dining_room_bulb_3_entity
    - light.dining_room_bulb_4_entity

- platform: group
  name: Playroom Lights
  unique_id: light.playroom_lights
  entities:
    - light.playroom_bulb_1_entity
    - light.playroom_bulb_2_entity
    - light.playroom_bulb_3_entity