- platform: rest
  resource: http://192.168.18.102:8126/container/jupyterlab
  name: JupyterLab
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_server
  name: Immich Server
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_redis
  name: Immich Redis
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_machine_learning
  name: Immich Machine Learning
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_postgres
  name: Immich Postgres
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  
- platform: rest
  resource: http://192.168.18.102:8126/container/duckdns
  name: DuckDNS
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'