- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/rainfall
  name: Local Rainfall
  value_template: >
    {% set ns = namespace(max_rain = 0) %}
    {% set readings = value_json.data.readings[0].data %}
    {# max of Geylang East Central, Towner Road, Poole Road and Nicoll Highway #}
    {% for reading in readings %}
      {% if reading['stationId'] in ['S215','S123','S78','S119'] %}
        {% if reading['value'] > ns.max_rain %}
          {% set ns.max_rain = reading['value'] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{ ns.max_rain | round(1) }}
  unit_of_measurement: mm
  scan_interval: 600

- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/air-temperature
  name: Local Outdoor Temperature
  value_template: >
    {% set ns = namespace(totaltemp = 0) %}
    {% set readings = value_json.data.readings[0].data %}
    {% for reading in readings %}
      {% set ns.totaltemp = ns.totaltemp + reading['value'] %}
    {% endfor %}
    {% if readings | length > 0 %}
      {{ (ns.totaltemp | float(0) / readings | length) | round(1) }}
    {% else %}
      {% set all_temp = states.sensor | selectattr('attributes.device_class','defined') | selectattr('attributes.device_class','eq','temperature') | map(attribute = 'state') | list %}
      {% set ns = namespace(sum = 0) %}
      {% for temp in all_temp %}
        {% set ns.sum = ns.sum + temp | float(0) %}
      {% endfor %}
      {{ (ns.sum / (all_temp | length)) | round(2) }}
    {% endif %}
  unit_of_measurement: °C
  device_class: temperature
  scan_interval: 600
  
- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/relative-humidity
  name: Local Outdoor Humidity
  value_template: >
    {% set ns = namespace(totalhum = 0) %}
    {% set readings = value_json.data.readings[0].data %}
    {% for reading in readings %}
      {% set ns.totalhum = ns.totalhum + reading['value'] %}
    {% endfor %}
    {% if readings | length > 0 %}
      {{ (ns.totalhum | float(0) / readings | length) | round(1) }}
    {% else %}
      {% set all_hum = states.sensor | selectattr('attributes.device_class','defined') | selectattr('attributes.device_class','eq','humidity') | map(attribute = 'state') | list %}
      {% set ns = namespace(sum = 0) %}
      {% for hum in all_hum %}
        {% set ns.sum = ns.sum + hum | float %}
      {% endfor %}
      {{ (ns.sum / (all_hum | length)) | round(2) }}
    {% endif %}
  unit_of_measurement: '%'
  device_class: humidity
  scan_interval: 600

- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/wind-speed
  name: Local Wind Speed
  value_template: >
    {% set ns = namespace(total_speed = 0) %}
    {% set readings = value_json.data.readings[0].data %}
    {# mean of Kim Chuan Rd and Scotts Rd #}
    {% for reading in readings %}
      {% if reading['stationId'] in ['S43','S111'] %}
        {% set ns.total_speed = ns.total_speed + reading['value'] %}
      {% endif %}
    {% endfor %}
    {# convert from knots to km/h #}
    {{ ns.total_speed * 1.852 / 2 }}
  unit_of_measurement: km/h
  scan_interval: 600

- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/wind-direction
  name: Local Wind Bearing
  value_template: >
    {% set ns = namespace(total_degrees = 0) %}
    {% set readings = value_json.data.readings[0].data %}
    {# mean of Kim Chuan Rd and Scotts Rd #}
    {% for reading in readings %}
      {% if reading['stationId'] in ['S43','S111'] %}
        {% set ns.total_degrees = ns.total_degrees + reading['value'] %}
      {% endif %}
    {% endfor %}
    {{ ns.total_degrees / 2 }}
  unit_of_measurement: °
  scan_interval: 600

- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/two-hr-forecast
  name: Local Two Hour Forecast
  value_template: >
    {% if 'forecasts' in value_json.data['items'][0].keys() %}
      {% set forecasts = value_json.data['items'][0]['forecasts'] %}
      {% for forecast in forecasts %}
        {% if forecast['area'] == 'Geylang' %}
          {% if forecast['forecast'].split('(') | length > 1 %}
            {{ forecast['forecast'].split('(')[0][:-1] }}
            {% break %}
          {% else %}
            {{ forecast['forecast'] }}
            {% break %}
          {% endif %}
        {% endif %}
      {% endfor %}
    {% else %}
      unavailable
    {% endif %}
  scan_interval: 600

- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook
  name: Local Forecast Day 1
  unique_id: sensor.local_forecast_day_1
  value_template: "{{ value_json.data.records[0]['forecasts'][0]['timestamp'] }}"
  json_attributes_path: '$.data.records[0].forecasts[0]'
  json_attributes:
    - forecast
    - temperature
    - relativeHumidity
    - wind
    - timestamp
  scan_interval: 600

- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook
  name: Local Forecast Day 2
  unique_id: sensor.local_forecast_day_2
  value_template: "{{ value_json.data.records[0]['forecasts'][1]['timestamp'] }}"
  json_attributes_path: '$.data.records[0].forecasts[1]'
  json_attributes:
    - forecast
    - temperature
    - relativeHumidity
    - wind
    - timestamp
  scan_interval: 600
    
- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook
  name: Local Forecast Day 3
  unique_id: sensor.local_forecast_day_3
  value_template: "{{ value_json.data.records[0]['forecasts'][2]['timestamp'] }}"
  json_attributes_path: '$.data.records[0].forecasts[2]'
  json_attributes:
    - forecast
    - temperature
    - relativeHumidity
    - wind
    - timestamp
  scan_interval: 600

- platform: rest
  resource: https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook
  name: Local Forecast Day 4
  unique_id: sensor.local_forecast_day_4
  value_template: "{{ value_json.data.records[0]['forecasts'][3]['timestamp'] }}"
  json_attributes_path: '$.data.records[0].forecasts[3]'
  json_attributes:
    - forecast
    - temperature
    - relativeHumidity
    - wind
    - timestamp
  scan_interval: 600

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80249
  name: Bus Stop Sims Drive Market
  unique_id: sensor.bus_stop_sims_drive_market
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 60
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['64','134','137'], 0) }}
  availability: "{{ value_json.Services is defined and value_json.Services | length > 0 }}"

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81081
  name: Bus Stop Opposite Aljunied Station
  unique_id: sensor.bus_stop_opposite_aljunied_station
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 60
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['40','125'], 0) }}
  availability: "{{ value_json.Services is defined and value_json.Services | length > 0 }}"

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81089
  name: Bus Stop Aljunied Station
  unique_id: sensor.bus_stop_aljunied_station
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 60
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['40','80','100'], 0) }}
  availability: "{{ value_json.Services is defined and value_json.Services | length > 0 }}"

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80091
  name: Bus Stop Before Lorong 23 Geylang
  unique_id: sensor.bus_stop_before_lorong_23_geylang
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 60
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['2','13','26','67'], 0) }}
  availability: "{{ value_json.Services is defined and value_json.Services | length > 0 }}"

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80031
  name: Bus Stop Kallang Station
  unique_id: sensor.bus_stop_kallang_station
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['2','13','51','63','67','80','100'], 4) }}
  availability: >
    {{ (states('zone.kallang_station_outer_perimeter') | int(0) > 0 
        or states('zone.kallang_station_bus_stop') | int(0) > 0)
       and value_json.Services is defined and value_json.Services | length > 0 }}
  
- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81111
  name: Bus Stop Paya Lebar Square
  unique_id: sensor.bus_stop_paya_lebar_square
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['137'], 4) }}
  availability: >
    {{ (states('zone.paya_lebar_outer_perimeter') | int(0) > 0 
        or states('zone.paya_lebar_station_bus_stops') | int(0) > 0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81119
  name: Bus Stop Opposite Paya Lebar Square
  unique_id: sensor.bus_stop_opposite_paya_lebar_square
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['134'], 4) }}
  availability: >
    {{ (states('zone.paya_lebar_outer_perimeter') | int(0) > 0
        or states('zone.paya_lebar_station_bus_stops') | int(0) > 0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81069
  name: Bus Stop Opposite Lorong 39 Geylang
  unique_id: sensor.bus_stop_opposite_lorong_39_geylang
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['137','40'], 4) }}
  availability: >
    {{ (states('zone.paya_lebar_outer_perimeter') | int(0) > 0 
        or states('zone.opposite_lorong_39_geylang_bus_stop') | int(0) >0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=82091
  name: Bus Stop Church of Our Lady Queen of Peace
  unique_id: sensor.bus_stop_church_of_our_lady_queen_of_peace
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['134','40'], 4) }}
  availability: >
    {{ (states('zone.paya_lebar_outer_perimeter') | int(0) > 0 
        or states('zone.church_of_our_lady_queen_of_peace_bus_stop') | int(0) > 0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=40089
  name: Bus Stop SCGS
  unique_id: sensor.bus_stop_scgs
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['48','67','170','960','972M'], 4) }}
  availability: >
    {{ (states('zone.schools_outer_perimeter') | int(0) > 0 
        or states('zone.scgs_bus_stop') | int(0) >0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=40069
  name: Bus Stop ACS
  unique_id: sensor.bus_stop_acs
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['48','67','170','960','972M'], 4) }}
  availability: >
    {{ (states('zone.schools_outer_perimeter') | int(0) > 0
        or states('zone.acs_bus_stop') | int(0) > 0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=92129
  name: Bus Stop Holy Family Church
  unique_id: sensor.bus_stop_holy_family_church
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['40'], 4) }}
  availability: >
    {{ (states('zone.marine_parade_outer_perimeter') | int(0) > 0
        or states('zone.holy_family_church_bus_stop') | int(0) > 0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=92119
  name: Bus Stop Roxy Square
  unique_id: sensor.bus_stop_roxy_square
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['40'], 4) }}
  availability: >
    {{ (states('zone.marine_parade_outer_perimeter') | int(0) > 0
        or states('zone.roxy_square_bus_stop') | int(0) > 0)
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=83141
  name: Bus Stop After Lorong G Telok Kurau
  unique_id: sensor.bus_stop_after_lorong_g_telok_kurau
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['155'], 4) }}
  availability: >
    {{ states('zone.telok_kurau') | int(0) > 0
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=83029
  name: Bus Stop After Kampong Eunos
  unique_id: sensor.bus_stop_after_kampong_eunos
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['155','2','26','67'], 4) }}
  availability: >
    {{ states('zone.telok_kurau') | int(0) > 0
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=40041
  name: Bus Stop Newton Station Exit C
  unique_id: sensor.bus_stop_newton_station_exit_c
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: >
    {% from 'transit.jinja' import bus_stop_next_buses %}
    {{ bus_stop_next_buses(value_json, ['48','67','170','960','972M'], 4) }}
  availability: >
    {{ states('zone.newton_station_exit_c_bus_stop') | int(0) > 0
       and value_json.Services is defined and value_json.Services | length > 0 }}

- platform: folder
  folder: /config/www/rain_radar/frames

- platform: folder
  folder: /config/www/rain_radar
  filter: 'rain_radar_animation_*.gif'

- platform: folder
  folder: /config/www/readme_graphics
  filter: 'animation_*.gif'

- platform: folder
  folder: /media/main_door_camera

- platform: statistics
  name: Rice Cooker Watts Recent Max
  unique_id: sensor.rice_cooker_watts_recent_max
  entity_id: sensor.rice_cooker_watts
  state_characteristic: value_max
  sampling_size: 30
  max_age:
    minutes: 8

- platform: time_date
  display_options:
    - time
    - date