- platform: rest
  resource: https://api.data.gov.sg/v1/environment/rainfall
  name: Local Rainfall
  value_template: >
    {% set ns = namespace(max_rain = 0) %}
    {% set readings = value_json['items'][0]['readings'] %}
    {# max of Geylang East Central, Towner Road, Poole Road and Nicoll Highway #}
    {% for reading in readings %}
      {% if reading['station_id'] in ['S215','S123','S78','S119'] %}
        {% if reading['value'] > ns.max_rain %}
          {% set ns.max_rain = reading['value'] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{ ns.max_rain | round(1) }}
  unit_of_measurement: mm
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/air-temperature
  name: Local Outdoor Temperature
  value_template: >
    {% set ns = namespace(totaltemp = 0) %}
    {% set readings = value_json['items'][0]['readings'] %}
    {% for reading in readings %}
      {% set ns.totaltemp = ns.totaltemp + reading['value'] %}
    {% endfor %}
    {% if readings | length > 0 %}
      {{ (ns.totaltemp | float(0) / readings | length) | round(1) }}
    {% else %}
      30
    {% endif %}
  unit_of_measurement: °C
  device_class: temperature
  scan_interval: 600
  
- platform: rest
  resource: https://api.data.gov.sg/v1/environment/relative-humidity
  name: Local Outdoor Humidity
  value_template: >
    {% set ns = namespace(totalhum = 0) %}
    {% set readings = value_json['items'][0]['readings'] %}
    {% for reading in readings %}
      {% set ns.totalhum = ns.totalhum + reading['value'] %}
    {% endfor %}
    {% if readings | length > 0 %}
      {{ (ns.totalhum | float(0) / readings | length) | round(1) }}
    {% else %}
      100
    {% endif %}
  unit_of_measurement: '%'
  device_class: humidity
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/2-hour-weather-forecast
  name: Local Two Hour Forecast
  value_template: >
    {% if 'forecasts' in value_json['items'][0].keys() %}
      {% set forecasts = value_json['items'][0]['forecasts'] %}
      {% for forecast in forecasts %}
        {% if forecast['area'] == 'Geylang' %}
          {% set geylang_forecast = forecast['forecast'] %}
          {% if geylang_forecast.split('(') | length > 1 %}
            {{geylang_forecast.split('(')[0][:-1]}}
          {% else %}
            {{ geylang_forecast}}
          {% endif %}
        {% endif %}
      {% endfor %}
    {% else %}
      unavailable
    {% endif %}
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 1
  unique_id: sensor.local_forecast_day_1
  value_template: "{{ value_json['items'][0]['forecasts'][0]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[0]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 2
  unique_id: sensor.local_forecast_day_2
  value_template: "{{ value_json['items'][0]['forecasts'][1]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[1]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind
    
- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 3
  unique_id: sensor.local_forecast_day_3
  value_template: "{{ value_json['items'][0]['forecasts'][2]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[2]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 4
  unique_id: sensor.local_forecast_day_4
  value_template: "{{ value_json['items'][0]['forecasts'][3]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[3]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind

- platform: statistics
  name: Rice Cooker Watts Recent Max
  unique_id: sensor.rice_cooker_watts_recent_max
  entity_id: sensor.rice_cooker_watts
  state_characteristic: value_max
  sampling_size: 30
  max_age:
    minutes: 8

- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_use_percent
    - type: swap_use_percent
    - type: processor_use
    - type: last_boot

- platform: folder
  folder: /config/www/rain_radar