- platform: rest
  resource: https://api.data.gov.sg/v1/environment/rainfall
  name: Local Rainfall
  value_template: >
    {% set ns = namespace(max_rain = 0) %}
    {% set readings = value_json['items'][0]['readings'] %}
    {# max of Geylang East Central, Towner Road, Poole Road and Nicoll Highway #}
    {% for reading in readings %}
      {% if reading['station_id'] in ['S215','S123','S78','S119'] %}
        {% if reading['value'] > ns.max_rain %}
          {% set ns.max_rain = reading['value'] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{ ns.max_rain | round(1) }}
  unit_of_measurement: mm
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/air-temperature
  name: Local Outdoor Temperature
  value_template: >
    {% set ns = namespace(totaltemp = 0) %}
    {% set readings = value_json['items'][0]['readings'] %}
    {% for reading in readings %}
      {% set ns.totaltemp = ns.totaltemp + reading['value'] %}
    {% endfor %}
    {% if readings | length > 0 %}
      {{ (ns.totaltemp | float(0) / readings | length) | round(1) }}
    {% else %}
      {% set all_temp = states.sensor | selectattr('attributes.device_class','defined') | selectattr('attributes.device_class','eq','temperature') | map(attribute = 'state') | list %}
      {% set ns = namespace(sum = 0) %}
      {% for temp in all_temp %}
        {% set ns.sum = ns.sum + temp | float(0) %}
      {% endfor %}
      {{ (ns.sum / (all_temp | length)) | round(2) }}
    {% endif %}
  unit_of_measurement: °C
  device_class: temperature
  scan_interval: 600
  
- platform: rest
  resource: https://api.data.gov.sg/v1/environment/relative-humidity
  name: Local Outdoor Humidity
  value_template: >
    {% set ns = namespace(totalhum = 0) %}
    {% set readings = value_json['items'][0]['readings'] %}
    {% for reading in readings %}
      {% set ns.totalhum = ns.totalhum + reading['value'] %}
    {% endfor %}
    {% if readings | length > 0 %}
      {{ (ns.totalhum | float(0) / readings | length) | round(1) }}
    {% else %}
      {% set all_hum = states.sensor | selectattr('attributes.device_class','defined') | selectattr('attributes.device_class','eq','humidity') | map(attribute = 'state') | list %}
      {% set ns = namespace(sum = 0) %}
      {% for hum in all_hum %}
        {% set ns.sum = ns.sum + hum | float %}
      {% endfor %}
      {{ (ns.sum / (all_hum | length)) | round(2) }}
    {% endif %}
  unit_of_measurement: '%'
  device_class: humidity
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/2-hour-weather-forecast
  name: Local Two Hour Forecast
  value_template: >
    {% if 'forecasts' in value_json['items'][0].keys() %}
      {% set forecasts = value_json['items'][0]['forecasts'] %}
      {% for forecast in forecasts %}
        {% if forecast['area'] == 'Geylang' %}
          {% set geylang_forecast = forecast['forecast'] %}
          {% if geylang_forecast.split('(') | length > 1 %}
            {{geylang_forecast.split('(')[0][:-1]}}
          {% else %}
            {{ geylang_forecast}}
          {% endif %}
        {% endif %}
      {% endfor %}
    {% else %}
      unavailable
    {% endif %}
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 1
  unique_id: sensor.local_forecast_day_1
  value_template: "{{ value_json['items'][0]['forecasts'][0]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[0]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 2
  unique_id: sensor.local_forecast_day_2
  value_template: "{{ value_json['items'][0]['forecasts'][1]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[1]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind
  scan_interval: 600
    
- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 3
  unique_id: sensor.local_forecast_day_3
  value_template: "{{ value_json['items'][0]['forecasts'][2]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[2]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind
  scan_interval: 600

- platform: rest
  resource: https://api.data.gov.sg/v1/environment/4-day-weather-forecast
  name: Local Forecast Day 4
  unique_id: sensor.local_forecast_day_4
  value_template: "{{ value_json['items'][0]['forecasts'][3]['timestamp'] }}"
  json_attributes_path: '$.items.[0].forecasts.[3]'
  json_attributes:
    - forecast
    - temperature
    - relative_humidity
    - wind
  scan_interval: 600

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80249&ServiceNo=64
  name: Sims Drive Market Bus 64
  unique_id: sensor.sims_drive_market_bus_64
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80249&ServiceNo=134
  name: Sims Drive Market Bus 134
  unique_id: sensor.sims_drive_market_bus_134
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80249&ServiceNo=137
  name: Sims Drive Market Bus 137
  unique_id: sensor.sims_drive_market_bus_137
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81081&ServiceNo=40
  name: Opposite Aljunied Station Bus 40
  unique_id: sensor.opposite_aljunied_station_bus_40
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81081&ServiceNo=125
  name: Opposite Aljunied Station Bus 125
  unique_id: sensor.opposite_aljunied_station_bus_125
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81089&ServiceNo=40
  name: Aljunied Station Bus 40
  unique_id: sensor.aljunied_station_bus_40
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81089&ServiceNo=80
  name: Aljunied Station Bus 80
  unique_id: sensor.aljunied_station_bus_80
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=81089&ServiceNo=100
  name: Aljunied Station Bus 100
  unique_id: sensor.aljunied_station_bus_100
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80091&ServiceNo=2
  name: Before Lorong 23 Geylang Bus 2
  unique_id: sensor.before_lorong_23_geylang_bus_2
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80091&ServiceNo=13
  name: Before Lorong 23 Geylang Bus 13
  unique_id: sensor.before_lorong_23_geylang_bus_13
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80091&ServiceNo=26
  name: Before Lorong 23 Geylang Bus 26
  unique_id: sensor.before_lorong_23_geylang_bus_26
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: rest
  resource: http://datamall2.mytransport.sg/ltaodataservice/BusArrivalv2?BusStopCode=80091&ServiceNo=67
  name: Before Lorong 23 Geylang Bus 67
  unique_id: sensor.before_lorong_23_geylang_bus_67
  headers:
    accountKey: !secret lta_datamall_apikey
  scan_interval: 172800
  value_template: "{{ (as_datetime(value_json['Services'][0]['NextBus']['EstimatedArrival']) - now()) // timedelta(minutes = 1) }}"
  unit_of_measurement: min
  json_attributes_path: $.Services.[0]
  json_attributes:
    - 'ServiceNo'
    - 'NextBus'
    - 'NextBus2'
    - 'NextBus3'

- platform: folder
  folder: /config/www/rain_radar/frames

- platform: folder
  folder: /config/www/rain_radar
  filter: 'rain_radar_animation_*.gif'

- platform: statistics
  name: Rice Cooker Watts Recent Max
  unique_id: sensor.rice_cooker_watts_recent_max
  entity_id: sensor.rice_cooker_watts
  state_characteristic: value_max
  sampling_size: 30
  max_age:
    minutes: 8

- platform: time_date
  display_options:
    - time
    - date