- platform: template
  switches:
    elenas_room_ac_switch:
      unique_id: switch.elenas_room_ac_switch
      value_template: "{{ is_state('binary_sensor.elenas_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.elenas_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.elenas_room_ac_set_state
          data:
            switch_on: true
            resync: true
      turn_off:
        - action: script.elenas_room_ac_set_state
          data:
            switch_on: false
            resync: true

    elis_room_ac_switch:
      unique_id: switch.elis_room_ac_switch
      value_template: "{{ is_state('binary_sensor.elis_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.elis_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.elis_room_ac_set_state
          data:
            switch_on: true
            resync: true
      turn_off:
        - action: script.elis_room_ac_set_state
          data:
            switch_on: false
            resync: true

    dining_room_ac_switch:
      unique_id: switch.dining_room_ac_switch
      value_template: "{{ is_state('binary_sensor.dining_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.dining_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.dining_room_ac_set_state
          data:
            switch_on: true
            resync: true
      turn_off:
        - action: script.dining_room_ac_set_state
          data:
            switch_on: false
            resync: true
    
    living_room_ac_switch:
      unique_id: switch.living_room_ac_switch
      value_template: "{{ is_state('binary_sensor.living_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.living_room_ac_vent') in ['on','off'] }}"
      turn_on:  
        - action: script.living_room_ac_set_state
          data:
            switch_on: true
            resync: true
      turn_off:
        - action: script.living_room_ac_set_state
          data:
            switch_on: false
            resync: true
          
    study_room_ac_switch:
      unique_id: switch.study_room_ac_switch
      value_template: "{{ is_state('binary_sensor.study_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.study_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.study_room_ac_set_state
          data:
            switch_on: true
            resync: true
      turn_off:
        - action: script.study_room_ac_set_state
          data:
            switch_on: false
            resync: true

    parents_room_ac_switch:
      unique_id: switch.parents_room_ac_switch
      value_template: "{{ is_state('binary_sensor.parents_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.parents_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.parents_room_ac_set_state
          data:
            switch_on: true
            resync: true
      turn_off:
        - action: script.parents_room_ac_set_state
          data:
            switch_on: false
            resync: true

- platform: rest
  resource: http://192.168.18.102:8126/container/jupyterlab
  name: JupyterLab
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_server
  name: Immich Server
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_redis
  name: Immich Redis
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_machine_learning
  name: Immich Machine Learning
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.18.102:8126/container/immich_postgres
  name: Immich Postgres
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  headers:
    Content-Type: application/json
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'