- platform: template
  switches:
    dining_room_ac_switch:
      unique_id: switch.dining_room_ac_switch
      value_template: "{{ is_state('input_boolean.dining_room_ac_power','on') }}"
      availability_template: "{{ states(input_boolean.dining_room_ac_power' in ['on','off']) }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.dining_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.dining_room_ac_power
    
    elis_room_ac_switch:
      unique_id: switch.elis_room_ac_switch
      value_template: "{{ is_state('input_boolean.elis_room_ac_power','on') }}"
      availability_template: "{{ states(input_boolean.elis_room_ac_power' in ['on','off']) }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.elis_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.elis_room_ac_power

    elenas_room_ac_switch:
      unique_id: switch.elenas_room_ac_switch
      value_template: "{{ is_state('input_boolean.elenas_room_ac_power','on') }}"
      availability_template: "{{ states(input_boolean.elenas_room_ac_power' in ['on','off']) }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.elenas_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.elenas_room_ac_power

    living_room_ac_switch:
      unique_id: switch.living_room_ac_switch
      value_template: "{{ is_state('input_boolean.living_room_ac_power','on') }}"
      availability_template: "{{ states(input_boolean.living_room_ac_power' in ['on','off']) }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.living_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.living_room_ac_power
          
    study_room_ac_switch:
      unique_id: switch.study_room_ac_switch
      value_template: "{{ is_state('input_boolean.study_room_ac_power','on') }}"
      availability_template: "{{ states(input_boolean.study_room_ac_power' in ['on','off']) }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.study_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.study_room_ac_power

    parents_room_ac_switch:
      unique_id: switch.parents_room_ac_switch
      value_template: "{{ is_state('input_boolean.parents_room_ac_power','on') }}"
      availability_template: "{{ states(input_boolean.parents_room_ac_power' in ['on','off']) }}"
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.parents_room_ac_power
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.parents_room_ac_power