- platform: template
  switches:
    elenas_room_ac_switch:
      unique_id: switch.elenas_room_ac_switch
      value_template: "{{ is_state('binary_sensor.elenas_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.elenas_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.elenas_room_ac_set_state
          data:
            switch_on: true
      turn_off:
        - action: script.elenas_room_ac_set_state
          data:
            switch_on: false

    elis_room_ac_switch:
      unique_id: switch.elis_room_ac_switch
      value_template: "{{ is_state('binary_sensor.elis_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.elis_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.elis_room_ac_set_state
          data:
            switch_on: true
      turn_off:
        - action: script.elis_room_ac_set_state
          data:
            switch_on: false

    dining_room_ac_switch:
      unique_id: switch.dining_room_ac_switch
      value_template: "{{ is_state('binary_sensor.dining_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.dining_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.dining_room_ac_set_state
          data:
            switch_on: true
      turn_off:
        - action: script.dining_room_ac_set_state
          data:
            switch_on: false
    
    living_room_ac_switch:
      unique_id: switch.living_room_ac_switch
      value_template: "{{ is_state('binary_sensor.living_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.living_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.living_room_ac_set_state
          data:
            switch_on: true
      turn_off:
        - action: script.living_room_ac_set_state
          data:
            switch_on: false
          
    study_room_ac_switch:
      unique_id: switch.study_room_ac_switch
      value_template: "{{ is_state('binary_sensor.study_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.study_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.study_room_ac_set_state
          data:
            switch_on: true
      turn_off:
        - action: script.study_room_ac_set_state
          data:
            switch_on: false

    parents_room_ac_switch:
      unique_id: switch.parents_room_ac_switch
      value_template: "{{ is_state('binary_sensor.parents_room_ac_vent', 'on') }}"
      availability_template: "{{ states('binary_sensor.parents_room_ac_vent') in ['on','off'] }}"
      turn_on:
        - action: script.parents_room_ac_set_state
          data:
            switch_on: true
      turn_off:
        - action: script.parents_room_ac_set_state
          data:
            switch_on: false
