binary_sensor:
  - platform: homeassistant
    id: kitchen_blind_opened
    entity_id: binary_sensor.kitchen_blind_opened
    filters:
      - invert:
  - platform: homeassistant
    id: kitchen_blind_closed
    entity_id: binary_sensor.kitchen_blind_closed
    filters:
      - invert:

cover:
  platform: feedback
  name: Kitchen Blind ESPHome
  open_endstop: kitchen_blind_opened
  open_duration: 14.1s
  close_endstop: kitchen_blind_closed
  close_duration: 14.1s
  max_duration: 15s
  direction_change_wait_time: 1.5s
  open_action: 
    - homeassistant.service: 
        service: remote.send_command
        data:
          entity_id: remote.living_room_universal_remote
          device: Kitchen Blinds
          command: Up
  close_action: 
    - homeassistant.service: 
        service: remote.send_command
        data:
          entity_id: remote.living_room_universal_remote
          device: Kitchen Blinds
          command: Down
  stop_action: 
    - homeassistant.service: 
        service: remote.send_command
        data:
          entity_id: remote.living_room_universal_remote
          device: Kitchen Blinds
          command: Stop