blueprint:
  name: AC Set State
  description: Set AC power and temperature
  domain: automation
  input:
    ac:
      name: Air Conditioner
      description: Air conditioner unit for which to set the state
      selector:
        entity:
          domain: climate
    default_temp:
      name: Default Temperature
      description: Default temperature of the air conditioner when turned on. Must be higher than the Minimum Temperature.
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: °C
          mode: slider
      default: 27
    min_temp:
      name: Minimum Temperature
      description: Minimum temperature of the air conditioner. If the AC's target temperature is set below this, it will be turned off.
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: °C
          mode: slider
      default: 24
trigger:
  - platform: state
    entity_id: !input ac
    id: cooling
    to: cool
  - platform: state
    entity_id: !input ac
    id: power_off
    from: cool
  - platform: state
    entity_id: !input ac
    id: temperature_changed
    attribute: temperature
action:
  - variables:
      target_ac: !input ac
  - choose:
      - conditions:
          - condition: trigger
            id: cooling
        sequence:
          - service: script.ac_set_state
            data:
              target_ac: "{{ state_attr(target_ac, 'friendly_name') }}"
              target_ac_temp: "{{ state_attr(target_ac, 'temperature') }}"
      - conditions:
          - condition: trigger
            id: power_off
        sequence:
          - service: script.ac_set_state
            data:
              target_ac: "{{ state_attr(target_ac, 'friendly_name') }}"
              target_ac_power: false
      - conditions:
          - condition: trigger
            id: temperature_changed
        sequence:
          - if:
              - condition: numeric_state
                entity_id: !input ac
                attribute: temperature
                below: !input min_temp
            then:
              - service: climate.set_temperature
                data:
                  temperature: !input default_temp
                target:
                  entity_id: !input ac
              - service: climate.turn_off
                data: {}
                target:
                  entity_id: !input ac
              - service: script.ac_set_state
                data:
                  target_ac: "{{ state_attr(target_ac, 'friendly_name') }}"
                  target_ac_power: false
            else:
              - service: climate.turn_on
                data: {}
                target:
                  entity_id: !input ac
              - service: script.ac_set_state
                data:
                  target_ac: "{{ state_attr(target_ac, 'friendly_name') }}"
                  target_ac_temp: "{{ state_attr(target_ac, 'temperature') }}"
    default: []
mode: single
max_exceeded: silent
