blueprint:
  name: Fan Set State
  description: Depending on state changes in the Template Fan entities, pass the state parameters to the Fan Set State script to sync the actual state of the physical fans by sending the corresponding RF commands.
  domain: automation
  input:
    fan:
      name: Fan
      description: Fan for which to set the state.
      selector:
        entity:
          domain: fan
    motion_fan_automation:
      name: Motion Fan Automation
      description: Automation determining the fan's speed when turned on.
      selector:
        entity:
          domain: automation
trigger:
  - platform: state
    entity_id: !input fan
    id: power_off
    from: "on"
    to: "off"
  - platform: state
    entity_id: !input fan
    id: power_on
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input fan
    id: speed
    attribute: percentage
action:
  - variables:
      target_fan: !input fan
  - choose:
      - conditions:
          - condition: trigger
            id: speed
        sequence:
          - if:
              - condition: numeric_state
                entity_id: !input fan
                attribute: percentage
                below: "10"
            then:
              - action: fan.turn_off
                data: {}
                target:
                  entity_id: !input fan
              - action: script.fan_set_state
                data:
                  target_fan: "{{ state_attr(target_fan,'friendly_name') }}"
                  target_fan_power: false
            else:
              - condition: state
                entity_id: !input fan
                state: "on"
              - action: script.fan_set_state
                data:
                  target_fan: "{{ state_attr(target_fan,'friendly_name') }}"
                  target_fan_speed: "{{ state_attr(target_fan, 'percentage') | int }}"
      - conditions:
          - condition: trigger
            id: power_on
        sequence:
          - action: automation.trigger
            target:
              entity_id: !input motion_fan_automation
          - delay: 0.1
          - action: script.fan_set_state
            data:
              target_fan: "{{ state_attr(target_fan,'friendly_name') }}"
              target_fan_speed: "{{ state_attr(target_fan, 'percentage') | int }}"
              target_fan_power: true
      - conditions:
          - condition: trigger
            id: power_off
        sequence:
          - action: script.fan_set_state
            data:
              target_fan: "{{ state_attr(target_fan,'friendly_name') }}"
              target_fan_power: false
    default: []
mode: single
max_exceeded: silent
