blueprint:
  name: Motion Timeout
  description: Turn off a list of entities when no motion is detected for a certain amount of time.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: When no motion is detected by this sensor for the Number of Minutes below, the entities listed will be turned off.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    number_of_minutes:
      name: Number of Minutes
      description: Number helper indicating the number of minutes for the motion timeout.
      selector:
        entity:
          domain: input_number
    entities_list:
      name: Entities to Track
      description: A list of entities.  If the lights' state should not change when any of these entities are on even if motion is cleared, specify them here.  Otherwise, leave blank.
      selector:
        entity:
          multiple: true
      default: []
    doors_list:
      name: Doors to Track
      description: A list of doors or door groups.  If the entities should not turn off when all the doors are closed even if motion is cleared (useful in bedrooms when someone is sleeping), specify the doors here.  Otherwise, leave blank.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true
      default: []
    turnoff_entities_list:
      name: Entities to Turn Off
      description: List of entities to turn off on timeout.
      selector:
        entity:
          multiple: true
trigger_variables:
  minutes_input_number: !input number_of_minutes
  doors: !input doors_list
  entities: !input entities_list
trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: "{{ states(minutes_input_number) | int(15) }}"
      seconds: 0
condition:
  - condition: template
    value_template: "{{ doors | length == 0 or 'on' in states | selectattr('entity_id', 'in', doors) | map(attribute = 'state') | list }}"
  - condition: template
    value_template: >
      {{ not 'on' in states | selectattr('entity_id', 'in', entities) | map(attribute = 'state') | list }}
action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: !input turnoff_entities_list
mode: single
