blueprint:
  name: Motion Timeout
  description: Turn off a list of entities when no motion is detected for a certain amount of time depending on whether the doors are closed.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: When no motion is detected by all these sensors for the Number of Minutes below, the entities listed will be turned off.
      selector:
        entity:
          domain: binary_sensor
          device_class: 
            - motion
            - occupancy
    number_of_minutes_door_closed:
      name: Number of Minutes - Door Closed
      description: Number helper indicating the number of minutes for the motion timeout when door is closed.
      selector:
        entity:
          domain: input_number
      default: input_number.motion_timeout_presence
    number_of_minutes_door_open:
      name: Number of Minutes - Door Open
      description: Number helper indicating the number of minutes for the motion timeout when door is open. If door is closed at this point in time, the automation will skip turning off the entities. Set to the same as Number of Minutes - Door Closed if Door to Track below is blank.
      selector:
        entity:
          domain: input_number
      default: input_number.motion_timeout_presence
    entities_list:
      name: Entities to Track
      description: A list of entities.  If the entities' state should not change when any of these entities are on even if motion is cleared, specify them here.  Otherwise, leave blank.
      selector:
        entity:
          multiple: true
      default: []
    door:
      name: Door to Track
      description: A door or door group.  If the entities should turn off after different times depending on whether the door is closed when motion is cleared (useful in bedrooms when someone is sleeping), specify the door here.  Otherwise, leave blank.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
      default: ''
    turnoff_entities_list:
      name: Entities to Turn Off
      description: List of entities to turn off on timeout.
      selector:
        entity:
          multiple: true
trigger_variables:
  minutes_door_open: !input number_of_minutes_door_open
  minutes_door_closed: !input number_of_minutes_door_closed
  entities: !input entities_list
trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: 'on'
    to: 'off'
    for:
      minutes: "{{ states(minutes_door_open) | int }}"
    id: timeout_doors_open
  - platform: state
    entity_id: !input motion_sensor
    from: 'on'
    to: 'off'
    for:
      minutes: "{{ states(minutes_door_closed) | int }}"
    id: timeout_doors_closed
condition:
  - condition: template
    value_template: >
      {{ not 'on' in states | selectattr('entity_id', 'in', entities) | map(attribute = 'state') | list }}
action:
  - variables:
      door_entity: !input door
  - delay: 1
  - condition: template
    value_template: >
      {{ trigger.id != "timeout_doors_open"
         or (door_entity | length == 0 
             or (is_state(door_entity, 'on')
                 and now() - states[door_entity].last_changed >= timedelta(minutes = (states(minutes_door_open) | int )))) }}
  - repeat:
      for_each: !input turnoff_entities_list
      sequence:
        - variables:
            repeat_entity: "{{ repeat.item }}"
        - repeat:
            while: "{{ states(repeat_entity) != 'off' and repeat.index <= 5 }}"
            sequence:
              - action: homeassistant.turn_off
                target:
                  entity_id: "{{ repeat_entity }}"
              - delay: 1
mode: single
max_exceeded: silent