blueprint:
  name: Motion Fan
  description: Control the fan when motion is detected, depending on whether the doors are open.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: When motion is detected by this sensor, the fan will be turned on.
      selector:
        entity:
          domain: binary_sensor
          device_class: 
            - motion
            - occupancy
    fan:
      name: Fan
      description: Fan to control.
      selector:
        entity:
          domain: fan
    off_hours_start:
      name: Off Hours Start
      description: A time helper indicating when the fan should be off.  If the fan never needs to be off, set this to the same time as Off Hours End.
      selector:
        entity:
          domain: input_datetime
      default: input_datetime.sleep_hours_end
    off_hours_end:
      name: Off Hours End
      description: A time helper indicating when the fan no longer needs to be off.
      selector:
        entity:
          domain: input_datetime
      default: input_datetime.sleep_hours_end
    entities_list:
      name: Entities to Track
      description: A list of entities.  If the fan's state should not change when any of these entities are on even if motion is detected, specify them here.  Otherwise, leave blank.
      selector:
        entity:
          multiple: true
      default: []
    doors_list:
      name: Doors to Track
      description: A list of doors or door groups.  If the fan's state should not change when all the doors are closed even if motion is detected (useful in bedrooms when someone is sleeping), specify the doors here.  Otherwise, leave blank.
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true
      default: []
    respect_closed_doors:
      name: Respect Closed Doors
      description: Set to true if the fan's state should not change when all the doors are closed even if motion is detected (useful in bedrooms when someone is sleeping).  Otherwise, set to false.
      selector:
        boolean:
      default: true
trigger_variables:
  entities: !input entities_list
  doors: !input doors_list
  respect_doors: !input respect_closed_doors
trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not respect_doors or doors | length == 0 or 'on' in states | selectattr('entity_id', 'in', doors) | map(attribute = 'state') | list }}"
      - condition: time
        after: input_datetime.sleep_hours_start
        before: input_datetime.sleep_hours_end
  - condition: template
    value_template: "{{ not 'on' in states | selectattr('entity_id', 'in', entities) | map(attribute = 'state') | list }}"
action:
  - delay: 0.05
  - condition: time
    after: !input off_hours_end
    before: !input off_hours_start
  - action: script.fan_controller
    data:
      fan: !input fan
      command: fan_on
  - delay: 1
  - action: script.fan_controller
    data:
      fan: !input fan
      command: fan_auto_control
mode: single
max_exceeded: silent
