select:
  - platform: template
    name: Status
    id: status_sensor
    restore_value: true
    optimistic: true
    
sensor:
  - platform: duty_time
    id: total_run_duration
    name: Total Run Duration
    unit_of_measurement: s
    device_class: duration
    last_time:
      name: Latest Run Duration

text:
  - platform: template
    id: latest_run_started_text
    mode: text
    max_length: 25
    optimistic: true
    restore_value: true
  - platform: template
    id: latest_run_ended_text
    mode: text
    max_length: 25
    optimistic: true
    restore_value: true
    
text_sensor:
  - platform: template
    id: latest_run_started
    name: Latest Run Started
    lambda: 'return id(latest_run_started_text).state.c_str();'
    device_class: timestamp
  - platform: template
    id: latest_run_ended
    name: Latest Run Ended
    lambda: 'return id(latest_run_ended_text).state.c_str();'
    device_class: timestamp
    
switch:
  - id: !extend relay
    on_turn_on:
      then:
        - select.set:
            id: status_sensor
            option: Standby
    on_turn_off:
      then:
        - select.set:
            id: status_sensor
            option: "Off"