sensor:
  - platform: sht3xd
    temperature:
      name: Temperature
      id: room_temp
    humidity:
      name: Humidity
      id: room_hum
  - platform: qmp6988
    pressure:
      name: Pressure
      id: pressure