sensor:
  - id: !extend target1_x
    internal: true
  - id: !extend target1_y
    internal: true
  - id: !extend target1_speed
    internal: true
  - id: !extend target1_resolution
    internal: true
  - id: !extend target1_angle
    internal: true
  - id: !extend target1_distance
    internal: true
  - id: !extend target2_x
    internal: true
  - id: !extend target2_y
    internal: true
  - id: !extend target2_speed
    internal: true
  - id: !extend target2_resolution
    internal: true
  - id: !extend target2_angle
    internal: true
  - id: !extend target2_distance
    internal: true
  - id: !extend target3_x
    internal: true
  - id: !extend target3_y
    internal: true
  - id: !extend target3_speed
    internal: true
  - id: !extend target3_resolution
    internal: true
  - id: !extend target3_angle
    internal: true
  - id: !extend target3_distance
    internal: true
