esp32_ble:
  io_capability: none
  max_notifications: 30
  max_connections: 4
  
ble_client:
  - mac_address: "FD:6C:B0:A1:4E:E4"       # <-- Replace with your shaver's MAC
    id: shaver
    auto_connect: true
    on_connect:
      then:
        - logger.log: "Connected to shaver"
    on_disconnect:
      then:
        - logger.log: "Disconnected from shaver"

external_components:
  - source:
      type: git
      url: https://github.com/mtheli/philips_shaver
      ref: main
      path: esphome/components
    components: [philips_shaver]
    refresh: 0s                  # always fetch latest code on build

philips_shaver:
  ble_client_id: shaver
  connected:
    name: "Shaver Connected"
