blueprint:
  name: AC Set State
  description: Turn on or off the AC
  domain: script
  input:
    air_conditioner:
      name: Air Conditioner
      description: Air conditioner unit to turn on or off
      selector:
        select:
          options:
            - label: Parents' Room AC
              value: climate.parents_room_ac
            - label: Study Room AC
              value: climate.study_room_ac
            - label: Living Room AC
              value: climate.living_room_ac
            - label: Dining Room AC
              value: climate.dining_room_ac
            - label: Eli's Room AC
              value: climate.elis_room_ac
            - label: Elena's Room AC
              value: climate.elenas_room_ac
fields:
  switch_on:
    selector:
      boolean:
    name: Switch On
    description: Switch on or off the AC
    required: true
    default: false
variables:
  ac: !input air_conditioner
  ac_remote:
    climate.parents_room_ac: remote.parents_room_universal_remote
    climate.study_room_ac: remote.study_room_universal_remote
    climate.living_room_ac: remote.living_room_universal_remote
    climate.dining_room_ac: remote.living_room_universal_remote
    climate.elis_room_ac: remote.elis_room_universal_remote
    climate.elenas_room_ac: remote.elenas_room_universal_remote
sequence:
  - action: remote.send_command
    target:
      entity_id: "{{ ac_remote[ac] }}"
    data:
      device: AC
      command: "{{ 24 if switch_on else 'Off' }}"
mode: queued
max: 10
