substitutions:
  name: athom-smart-plug-0fff96
packages:
  athom.smart-plug: github://athom-tech/athom-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: XQFmQPLYHuMCS3CqIi+ME82zYqRkzAzghWG8x4bCG2s=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
