substitutions:
  name: athom-presence-sensor-f9a559
  friendly_name: Kitchen Radar
packages:
  Athom_Technology.Presence_Sensor: github://athom-tech/athom-configs/athom-presence-sensor.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: G1ZnqnDXraeGRo+4X0/3BIuuvcxBCdW2tLaUJE28GTs=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
