substitutions:
  name: athom-presence-sensor-f9a55a
  friendly_name: Living Room Radar
packages:
  Athom_Technology.Presence_Sensor: github://athom-tech/athom-configs/athom-presence-sensor.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret living_room_radar_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.18.50
    gateway: 192.168.18.1
    subnet: 255.255.255.0