api:
  encryption:
    key: "s9E8YcPZ2Nmxmyqwpm/bJcDVa+rF65chaOVbJfnk/no="

substitutions:
  name: athom-smart-plug-v2-ebd1d1
  friendly_name: Dishwasher

packages:
  Athom Technology.Smart Plug V2: "github://athom-tech/athom-configs/athom-smart-plug-v2.yaml"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
