substitutions:
  name: athom-smart-plug-v2-ebd1d1
  friendly_name: Dishwasher
  sntp_server_1: "192.168.18.1"
  
api:
  encryption:
    key: !secret dishwasher_api_key

packages:
  Athom Technology.Smart Plug V2: "github://athom-tech/athom-configs/athom-smart-plug-v2.yaml"
  appliance_plug: !include packages/appliance_plug.yaml
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server: !remove

select:
  - id: !extend status_sensor
    options:
      - "Off"
      - Washing
      - Cooling
      - Standby

binary_sensor:
  - platform: homeassistant
    id: door
    entity_id: binary_sensor.dishwasher_door
    filters:
      - delayed_on: 1min
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_off: door
            then:
              - switch.turn_on: relay
            else:
              - if:
                  condition:
                    - binary_sensor.is_on: door
                  then:
                    - switch.turn_off: load_clean
  - platform: template
    id: idle
    lambda: "return id(relay).state == 'on' && id(power_sensor).state <= 5;"
    filters:
      - delayed_on: 15min
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: idle
            then:
              - if:
                  condition:
                    select.is:
                      id: status_sensor
                      options: Cooling
                  then:
                    switch.turn_on: load_clean
              - delay: 5s
              - switch.turn_off: relay
  - platform: template
    id: washing
    lambda: "return id(power_sensor).state > 5;"
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: washing
            then:
              - select.set:
                  id: status_sensor
                  option: Washing
            else:
              - if:
                  condition:
                    - binary_sensor.is_off: washing
                  then:
                    - if:
                        condition:
                          - select.is:
                              id: status_sensor
                              options: Washing
                        then:
                          - select.set:
                              id: status_sensor
                              option: Cooling
                        else:
                          - select.set:
                              id: status_sensor
                              option: Standby

sensor:
  - platform: duty_time
    id: current_run_duration
    name: Current Run Duration
    unit_of_measurement: s
    device_class: duration
    lambda: "return id(status_sensor).state == 'Washing';"
    last_time:
      name: Last Run Started
      device_class: timestamp
                              
switch:
  - platform: template
    id: load_clean
    name: Load Clean
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true