substitutions:
  name: athom-smart-plug-v2-8f39de
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  kitchen_blind: !include cover/kitchen_blind.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: LFocBb13DcaU8NZ7m3HzYnVxFJBz5ilZ4w9uUKaVr2M=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.18.34
    gateway: 192.168.18.1
    subnet: 255.255.255.0