substitutions:
  name: "athom-smart-plug-v2-8f39de"
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: 96WEIymirVNHGsFpGFxPwMeKbDPVLwvDBuvdVcJaJ2I=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
