substitutions:
  name: athom-smart-plug-v2-ebd1d1
  friendly_name: Dishwasher

api:
  encryption:
    key: !secret dishwasher_api_key

packages:
  Athom Technology.Smart Plug V2: "github://athom-tech/athom-configs/athom-smart-plug-v2.yaml"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: run_started
    type: time_t
    restore_value: true
    initial_value: '0'
  - id: run_ended
    type: time_t
    restore_value: true
    initial_value: '0'

select:
  - platform: template
    name: Status
    id: dishwasher_status
    options:
      - "Off"
      - Washing
      - Cooling
      - standby
    restore_value: true
    optimistic: true
  
binary_sensor:
  - platform: homeassistant
    id: door
    entity_id: binary_sensor.dishwasher_door
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_off: door
            then:
              - switch.turn_on: relay
            else:
              - if:
                  condition:
                    - binary_sensor.is_on: door
                  then:
                    - switch.turn_off: load_clean
  - platform: template
    id: idle
    lambda: "return id(relay).state == 'on' && id(power_sensor).state <= 5;"
    filters:
      - delayed_on: 15min
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: idle
            then:
              - if:
                  condition:
                    select.is:
                      id: dishwasher_status
                      options: Cooling
                  then:
                    switch.turn_on: load_clean
              - delay: 5s
              - switch.turn_off: relay
  - platform: template
    id: washing
    lambda: "return id(power_sensor).state > 5"
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: washing
            then:
              - select.set:
                  id: dishwasher_status
                  option: Washing
            else:
              - if:
                  condition:
                    - binary_sensor.is_off: washing
                  then:
                    - if:
                        condition:
                          - select.is:
                              id: dishwasher_status
                              options: Washing
                        then:
                          - select.set:
                              id: dishwasher_status
                              option: Cooling
                        else:
                          - select.set:
                              id: dishwasher_status
                              option: Standby

switch:
  - platform: template
    id: load_clean
    name: Load Clean
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
  - id: !extend relay
    on_state:
      then:
        - if:
            condition:
              - switch.is_off: relay
            then:
              - select.set:
                  id: dishwasher_status
                  option: "Off"