esphome:
  name: doorbell
  friendly_name: Doorbell

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret doorbell_api_key

ota:
  - platform: esphome
    password: !secret doorbell_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.18.36
    gateway: 192.168.18.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell"
    password: !secret ap_password

captive_portal:
  
binary_sensor:
  - platform: gpio
    name: Motion
    id: motion
    device_class: motion
    pin: 12
  - platform: gpio
    name: Button
    id: button
    pin: 
      number: 3
      inverted: True
    filters:
      - delayed_off: 10s

light:
  - platform: neopixelbus
    id: hex_light
    name: Hex Light
    type: GRB
    variant: ws2812x
    num_leds: 37
    pin: 4
    effects:
      - addressable_lambda:
          name: Right Arrow
          update_interval: 0.1s
          lambda: |-
            // set background
            it.all() = Color::WHITE;
            it.range(9,28) = Color(0, 0, 255);

            // animate
            static uint16_t progress = 0;
            if (progress > 6) {
              progress = 0;
            }

            if (progress == 6) {
              it[15] = Color::WHITE;
            } else {
              it[progress + 9] = Color::WHITE;
              it[progress + 16] = Color::WHITE;
              it[progress + 22] = Color::WHITE;
            }

            progress = progress + 1;
      - addressable_lambda:
          name: Wait
          update_interval: 0.25s
          lambda: |-
            // set background
            it.all() = Color::WHITE;
            int blue_ring[12] = {5,6,7,13,20,26,31,30,29,23,16,10};
            for (int i = 0; i < 12; i++) {
              it[blue_ring[i]] = Color(0,0,255);
            }

            // animate
            static uint16_t progress = 0;
            if (progress > 11) {
              progress = 0;
            }

            if (progress == 11) {
              it[blue_ring[progress]] = Color::WHITE;
              it[blue_ring[0]] = Color::WHITE;
            } else {
              it[blue_ring[progress]] = Color::WHITE;
              it[blue_ring[progress + 1]] = Color::WHITE;
            }

            progress = progress + 1;
      - addressable_lambda:
          name: Heart
          update_interval: 0.5s
          lambda: |-
            // set black background
            it.all() = Color::WHITE;
            // small heart
            it[5] = Color(255,0,0);
            it[7] = Color(255,0,0);
            it.range(10,14) = Color(255,0,0);
            it.range(17,20) = Color(255,0,0);
            it.range(24,26) = Color(255,0,0);
            it[30] = Color(255,0,0);
                                    
            //animate
            static uint16_t progress = 0;
            if (progress > 1) {
              progress = 0;
            }
            if (progress == 1) {
              // add pixels for big heart
              it[0] = Color(255,0,0);
              it[3] = Color(255,0,0);
              it[4] = Color(255,0,0);
              it[8] = Color(255,0,0);
              it[9] = Color(255,0,0);
              it[14] = Color(255,0,0);
              it[16] = Color(255,0,0);
              it[20] = Color(255,0,0);
              it[23] = Color(255,0,0);
              it[26] = Color(255,0,0);
              it[29] = Color(255,0,0);
              it[31] = Color(255,0,0);
              it[34] = Color(255,0,0);
              it[35] = Color(255,0,0);
            }
            progress = progress + 1;
            