substitutions:
  name: elenas_room_radar
  friendly_name: Elena's Room Radar
  illuminance_update_interval: "2s"
  log_level: INFO
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
  epl_target_sensors_internal: !include packages/epl_target_sensors_internal.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret elenas_room_radar_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.18.57
    gateway: 192.168.18.1
    subnet: 255.255.255.0

esp32:
  framework:
    # workaround for 2024.12 compile issue @ https://github.com/esphome/wake-word-voice-assistants/issues/42#issuecomment-2550985988
    version: 4.4.8 
    platform_version: 5.4.0
    
sensor:
  - id: !extend illuminance_sensor
    name: Lux
    filters:
      - lambda: "return 3 * x + id(illuminance_offset_ui).state;"
