substitutions:
  name: "elis-watch-charger"
  friendly_name: "Eli's Watch Charger"
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret elis_watch_charger_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.18.32
    gateway: 192.168.18.1
    subnet: 255.255.255.0

web_server: !remove