substitutions:
  name: elis_room_radar
  friendly_name: Eli's Room Radar
  illuminance_update_interval: "2s"
  log_level: INFO
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret elis_room_radar_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.18.54
    gateway: 192.168.18.1
    subnet: 255.255.255.0

sensor:
  - id: !extend illuminance_sensor
    name: Lux
    filters:
      - lambda: "return 2 * x + id(illuminance_offset_ui).state;"
  - id: !extend target1_x
    entity_category: config
    internal: true
  - id: !extend target1_y
    entity_category: config
    internal: true
  - id: !extend target1_speed
    entity_category: config
    internal: true
  - id: !extend target1_resolution
    entity_category: config
    internal: true
  - id: !extend target2_x
    entity_category: config
    internal: true
  - id: !extend target2_y
    entity_category: config
    internal: true
  - id: !extend target2_speed
    entity_category: config
    internal: true
  - id: !extend target2_resolution
    entity_category: config
    internal: true
  - id: !extend target3_x
    entity_category: config
    internal: true
  - id: !extend target3_y
    entity_category: config
    internal: true
  - id: !extend target3_speed
    entity_category: config
    internal: true
  - id: !extend target3_resolution
    entity_category: config
    internal: true
  - id: !extend target1_angle
    entity_category: config
    internal: true
  - id: !extend target2_angle
    entity_category: config
    internal: true
  - id: !extend target3_angle
    entity_category: config
    internal: true
  - id: !extend target1_distance
    entity_category: config
    internal: true
  - id: !extend target2_distance
    entity_category: config
    internal: true
  - id: !extend target3_distance
    entity_category: config
    internal: true
