esphome:
  name: kitchen-core
  friendly_name: Kitchen Core

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "jKDrsPRb68XF+5yXJOackIhJ3Ncgr9FoxvikUMEz/Rw="

ota:
  - platform: esphome
    password: "0c11b112e73267e39c271e7181f3334e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen-Core Fallback Hotspot"
    password: "kv5wL8sE7d18"

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin: 37
    name: Front Button
    id: front_button
    filters: 
      - invert:
  - platform: gpio
    pin: 39
    name: Side Button
    id: side_button
    filters: 
      - invert:
