esphome:
  name: kitchen-core
  friendly_name: Kitchen Core

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "jKDrsPRb68XF+5yXJOackIhJ3Ncgr9FoxvikUMEz/Rw="

ota:
  - platform: esphome
    password: "0c11b112e73267e39c271e7181f3334e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen-Core Fallback Hotspot"
    password: "kv5wL8sE7d18"
  
  manual_ip:
    static_ip: 192.168.18.18
    gateway: 192.168.18.1
    subnet: 255.255.255.0

captive_portal:

i2c:
  - id: i2c_internal
    sda: 21
    scl: 22
  - id: i2c_hat
    sda: 0
    scl: 26
  
binary_sensor:
  - platform: gpio
    pin: 37
    name: Front Button
    id: front_button
    filters: 
      - invert:
  - platform: gpio
    pin: 39
    name: Side Button
    id: side_button
    filters: 
      - invert:
