substitutions:
  name: living_room_ac
  friendly_name: "Living Room AC"
  min_temp: 16
  max_temp: 29
  tx: 17
  rx: 18
  external_temp_sensor: sensor.living_room_temperature
  external_hum_sensor: sensor.living_room_humidity

esphome:
  name: living-room-ac
  friendly_name: Living Room AC

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: 5.4.0 # workaround for ESPHome UART issue after 2025.8 https://github.com/echavet/MitsubishiCN105ESPHome/issues/378

# Enable Home Assistant API
api:
  encryption:
    key: !secret living_room_ac_api_key

ota:
  - platform: esphome
    password: !secret living_room_ac_ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      # bssid: 34:97:f6:22:df:28

  manual_ip:
    static_ip: 192.168.18.65
    gateway: 192.168.18.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living Room AC"
    password: !secret ap_password

captive_portal:

# Default logging level
logger:
  level: INFO

packages:
  aircon: !include packages/aircon.yaml