substitutions:
  name: dining_room_speaker
  friendly_name: Dining Room Speaker
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: t/6rXxAUIiSJZyLEjfmuV14abU3/sMwION+Vtxyp6kI=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
