esphome:
  name: main-door-camera
  friendly_name: Main Door Camera

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret main_door_camera_api_key

ota:
  - platform: esphome
    password: !secret main_door_camera_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Main-Door-Camera"
    password: !secret ap_password

  manual_ip:
    static_ip: 192.168.18.58
    gateway: 192.168.18.1
    subnet: 255.255.255.0

captive_portal:
    
binary_sensor:
  - platform: gpio
    id: motion
    name: Motion
    pin: 13
    device_class: motion
    publish_initial_state: true
    filters:
      - delayed_off: 20s
    on_press: 
      then:
        - light.turn_on: 
            id: led
            effect: pulse
    on_release: 
      then:
        - light.turn_off: led

output:
  - platform: ledc
    pin: 14
    inverted: true
    id: led_output

light:
  - platform: monochromatic
    output:  led_output
    name: LED
    id: led
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 10%
          max_brightness: 100%

esp32_camera:
  id: camera
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO22
    scl: GPIO23
  data_pins: [GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO25
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  max_framerate: 2 fps
  jpeg_quality: 20
  brightness: 1

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot