substitutions:
  name: rice-cooker
  sntp_server_1: "192.168.18.1"
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  friendly_name: Rice Cooker
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret rice_cooker_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.18.34
    gateway: 192.168.18.1
    subnet: 255.255.255.0

web_server: !remove

globals:
  - id: run_started
    type: time_t
    restore_value: true
    initial_value: '0'
  - id: run_ended
    type: time_t
    restore_value: true
    initial_value: '0'

select:
  - platform: template
    name: Status
    id: rice_cooker_status
    options:
      - "Off"
      - Cooking
      - Warming
      - Standby
    optimistic: true
    restore_value: true
    on_value:
      then:
        - if:
            condition:
              select.is:
                id: rice_cooker_status
                options: Cooking
            then:
              - text_sensor.template.publish:
                  id: last_run_started
                  state: !lambda 'return id(sntp_time).utcnow().strftime("%Y-%m-%dT%H:%M:%SZ");'
              - lambda: "id(run_started) = id(sntp_time).utcnow().timestamp;"
        - if:
            condition:
              select.is:
                id: rice_cooker_status
                options: Warming
            then:
              - text_sensor.template.publish:
                  id: last_run_ended
                  state: !lambda 'return  id(sntp_time).utcnow().strftime("%Y-%m-%dT%H:%M:%SZ");'
              - lambda: "id(run_ended) = id(sntp_time).utcnow().timestamp;"

binary_sensor:
  - platform: template
    name: Running
    lambda: "return id(power_sensor).state > 0;"
  - platform: homeassistant
    entity_id: binary_sensor.rice_cooker_lid
    id: lid
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_off: lid
            then:
              - switch.turn_on: relay
  - platform: template
    id: cooking_to_standby
    lambda: "return id(power_sensor).state < 1.1 && id(power_sensor).state >= 0.3;"
    filters:
      - delayed_on: 60s
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: cooking_to_standby
            then:
            - select.set: 
                id: rice_cooker_status
                option: Standby
  - platform: template
    id: turn_off
    lambda: "return id(power_sensor).state <  0.3;"
    filters:
      - delayed_on: 15min
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: turn_off
            then:
            - switch.turn_off: relay
                
text_sensor:
  - platform: template
    name: Last Run Started
    id: last_run_started
    device_class: timestamp
  - platform: template
    name: Last Run Ended
    id: last_run_ended
    device_class: timestamp
    on_value:
      then:
        - if:
            condition:
              lambda: "return id(run_started) > id(run_ended);"
            then:
              sensor.template.publish:
                id: last_run_duration
                state: !lambda "return id(run_started) - id(run_ended);"

sensor:
  - platform: template
    name: Last Run Duration
    id: last_run_duration
    device_class: duration
  - platform: template
    id: watts_recent_max
    lambda: "return id(power_sensor).state;"
    update_interval: 10s
    filters:
      - max:
          window_size: 30
          send_every: 10
    on_value_range:
      - above: 200
        then:
          - select.set: 
              id: rice_cooker_status
              option: Cooking
      - above: 30
        below: 140
        then:
          - select.set: 
              id: rice_cooker_status
              option: Warming

switch:
  - id: !extend relay
    on_turn_on:
      - select.set: 
          id: rice_cooker_status
          option: Standby
    on_turn_off:
      - select.set:
          id: rice_cooker_status
          option: "Off"