substitutions:
  name: rice-cooker
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  friendly_name: Rice Cooker
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret rice_cooker_api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.18.34
    gateway: 192.168.18.1
    subnet: 255.255.255.0