substitutions:
  name: study_room_ac
  friendly_name: "Study Room AC"
  min_temp: 16
  max_temp: 29
  
esphome:
  name: study-room-ac
  friendly_name: Study Room AC

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: !secret study_room_ac_api_key

ota:
  - platform: esphome
    password: !secret study_room_ac_ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
#      bssid: 10:7B:44:AE:4C:A8

  manual_ip:
    static_ip: 192.168.18.64
    gateway: 192.168.18.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Study Room AC"
    password: !secret ap_password

captive_portal:
    
# Enable logging
logger:

sensor:
  - platform: dht
    pin: 22
    model: DHT22
    humidity:
      name: Humidity
      accuracy_decimals: 1
    temperature:
      name: Temperature
      id: temp_sensor
      on_value:
        then:
          - if:
              condition:
                - lambda: 'return id(ac).mode != CLIMATE_MODE_OFF;'
              then:
                - if:
                    condition:
                      - lambda: 'return (x - id(ac).target_temperature) > 2;'
                    then:
                      - if:
                          condition:
                            - lambda: 'return id(ac).fan_mode != CLIMATE_FAN_HIGH;'
                          then:
                            - climate.control:
                                id: ac
                                fan_mode: HIGH
                                target_temperature: !lambda 'return id(ac).target_temperature;'
                    else:
                      if:
                          condition: 
                            - lambda: 'return id(ac).fan_mode != CLIMATE_FAN_LOW;'
                          then:
                            - climate.control:
                                id: ac
                                fan_mode: LOW
                                target_temperature: !lambda 'return id(ac).target_temperature;'

remote_transmitter:
  pin: 23
  carrier_duty_percent: 50%

climate:
  - platform: mitsubishi
    name: AC
    id: ac
    sensor: temp_sensor
    set_fan_mode: quiet_4levels
    supports_heat: False
    supports_dry: True
    supports_fan_only: True
    vertical_default: up
    visual: 
      min_temperature: ${min_temp}
      max_temperature: ${max_temp}
      temperature_step: 0.5